### ISSUE TITLE
I'm having trouble going past Instagram home page. It doesn't proceed to URL

### ISSUE THREAD

**Issue by azlanmunir** [ScrPzz/IG_scraper#1]
DevTools listening on ws://127.0.0.1:52313/devtools/browser/91b1ac12-ee5b-4523-a7b3-665253460d20
Traceback (most recent call last):
  File "C:\Users\am1460\Downloads\InstagramScraper\scrape_likes.py", line 7, in <module>
    Driver, args = scraper.setup()
                   ^^^^^^^^^^^^^^^
  File "C:\Users\am1460\Downloads\InstagramScraper\src\likes_scraper.py", line 53, in setup
    driver = chrome_driver.make_IG_access_w_creds(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\am1460\Downloads\InstagramScraper\scripts\chrome_driver.py", line 75, in make_IG_access_w_creds
    wait.until(
  File "C:\Users\am1460\Downloads\insta-scrapper\myenv\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x007BA813+48355]
        (No symbol) [0x0074C4B1]
        (No symbol) [0x00655358]
        (No symbol) [0x006809A5]
        (No symbol) [0x00680B3B]
        (No symbol) [0x006AE232]
        (No symbol) [0x0069A784]
        (No symbol) [0x006AC922]
        (No symbol) [0x0069A536]
        (No symbol) [0x006782DC]
        (No symbol) [0x006793DD]
        GetHandleVerifier [0x00A1AABD+2539405]
        GetHandleVerifier [0x00A5A78F+2800735]
        GetHandleVerifier [0x00A5456C+2775612]
        GetHandleVerifier [0x008451E0+616112]
        (No symbol) [0x00755F8C]
        (No symbol) [0x00752328]
        (No symbol) [0x0075240B]
        (No symbol) [0x00744FF7]
        BaseThreadInitThunk [0x76A96BA9+25]
        RtlGetFullPathName_UEx [0x76FB8F9F+1215]
        RtlGetFullPathName_UEx [0x76FB8F6D+1165]

**Comment by ScrPzz** [comment]
Hi, judging by the error,most probably something on the html on the page has changed. 
Can you provide a more extensive description of the issue? 
- The command that gave that error;
- The page you are trying to scrape.
